import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'About',
      items: [{ type: 'autogenerated', dirName: 'about' }],
    },
    {
      type: 'category',
      label: 'Philosophy',
      items: [{ type: 'autogenerated', dirName: 'philosophy' }],
    },
    {
      type: 'category',
      label: 'Policy',
      items: [{ type: 'autogenerated', dirName: 'policy' }],
    },
    {
      type: 'category',
      label: 'Protocols',
      items: [{ type: 'autogenerated', dirName: 'protocols' }],
    },
    {
      type: 'category',
      label: 'Thought Leadership',
      items: [{ type: 'autogenerated', dirName: 'thought-leadership' }],
    },
  ],
};

export default sidebars;
